### ISSUE TITLE
ctable() still spits out totals even with totals = F

### ISSUE THREAD

**Issue by cspenn** [dcomtois/summarytools#68]
ctable() still spits out totals in the [["cross_table"]] with the totals flag set locally and globally with ctable.options = F.

R 3.5.3, summarytools 0.9.3.

`st_options(ctable.totals=FALSE)` is set right after package load.

`q2_4gender <-
  with(q2_4df, ctable(
    gender,
    q2_4,
    chisq = F,
    headings = T,
    totals = FALSE
  ))`

Example of local invocation.

The function suppresses totals in the output but not in the cross table, which I am trying to extract for a heat map.

**Comment by dcomtois** [comment]
Hi,

Yes, this is by design; it allows the override of the `totals` parameter when using the `print()` method. You can however suppress the last row this way:

`ct_no_totals <- q2_4gender$cross_table[-nrow(q2_4gender$cross_table),]`

Or simply use base R's `table()` instead of `ctable()`.

Cheers,

Dominic
