### ISSUE TITLE
special handling for dates

### ISSUE THREAD

**Issue by soodoku** [dcomtois/summarytools#8]
hola!

excited so a couple more suggestions: 

1. i think it would be to useful to allow for special handling of date and time vars. 
2. for categorical vars./char. vars. with more than 10 unique, it may be useful to present breakdown of 9 most common (as you do, I think) and then the 10th can be 'other or all else' (which totals up for everything other char. val. 

hth

**Comment by dcomtois** [comment]
It's a good point you bring for date and time variables. Been thinking about it, but up to now there was no request for it. Leaving it open and will try to find time for it.

For the 2nd point, what you describe is already implemented... Try reducing the max number of categories to display and you should have it. Otherwise can you pls paste results?

Thanks! :)

**Comment by soodoku** [comment]
nice! thanks.

**Comment by dcomtois** [comment]
If anyone wants to help with summarizing date and time vectors, please let me know.

**Comment by soodoku** [comment]
Both can be dealt with as numeric. 

For date/time: convert to date,time,seconds format

Get mean, median, min, max

sd can make sense. 

IQR, vald, missing, etc. can also work. so basically keep the format same as numeric.

**Comment by dcomtois** [comment]
Version 0.8.2 will support Date and POSIXt datetime objects. I stuck with min, median and max + histogram, we'll see how this goes!

**Comment by soodoku** [comment]
awesome! 👍
